name: i18n Pull Request

concurrency: ci-${{ github.ref }}

env:
  PROJECT_NAME: i18n

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  unit_tests:
    name: Unit Tests
    uses: ./.github/workflows/unit_tests.yaml
    secrets:
      FAVOR_COMPOSER_AUTH: ${{ secrets.FAVOR_COMPOSER_AUTH }}
