name: Unit Tests

on:
  workflow_call:
    secrets:
      FAVOR_COMPOSER_AUTH:
        description: "Composer auth token"
        required: true

jobs:
  unit_test:
    name: Unit Test
    runs-on: devops-prod-runner

    steps:
    - name: Check out code
      id: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build containers
      id: build
      env:
        COMPOSER_AUTH: ${{ secrets.FAVOR_COMPOSER_AUTH2 }}
      run: | 
        cd unit_tests
        docker compose down
        docker compose pull
        docker compose build
    
    - name: Run tests
      run: |
        cd unit_tests
        pwd
        docker compose run tests
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: ${{ !cancelled() }}
      with:
        name: Unit Test Results
        path: 'tests/results/unit/*.xml'
        reporter: java-junit
        fail-on-error: 'true'